// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { z } from "npm:zod@^3.23.8";
var SUPABASE_URL = "https://xcvlijchkmhjonhfildm.supabase.co";
var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdmxpamNoa21oam9uaGZpbGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDY3MDEsImV4cCI6MjA2MzE4MjcwMX0.3_FZWbV4qCqs1xQmh0Hws83xQxofSApzVRScSCEi9Pg";
var search_products_default = defineTool({
  name: "search_products",
  title: "Rechercher des produits",
  description: "Recherche des produits Rif Elegance (chapeaux en paille, sacs, accessoires) par mot-cl\xE9, cat\xE9gorie ou fourchette de prix. Retourne nom, prix, cat\xE9gorie, stock et slug.",
  inputSchema: {
    query: z.string().optional().describe("Mot-cl\xE9 recherch\xE9 dans le nom ou la description"),
    category: z.string().optional().describe('Filtrer par cat\xE9gorie exacte (ex: "chapeaux", "sacs")'),
    max_price: z.number().positive().optional().describe("Prix maximum en EUR"),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ query, category, max_price, limit }) => {
    const supabase = createClient(SUPABASE_URL, SUPABASE_ANON, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("products").select(
      "id, slug, name, price, category, short_description, stock_quantity, is_available, images"
    ).eq("is_active", true).limit(limit);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.eq("category", category);
    if (max_price) q = q.lte("price", max_price);
    const { data, error } = await q;
    if (error)
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    return {
      content: [
        { type: "text", text: `${data?.length ?? 0} produit(s) trouv\xE9(s).` }
      ],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z2 } from "npm:zod@^3.23.8";
var SUPABASE_URL2 = "https://xcvlijchkmhjonhfildm.supabase.co";
var SUPABASE_ANON2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdmxpamNoa21oam9uaGZpbGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDY3MDEsImV4cCI6MjA2MzE4MjcwMX0.3_FZWbV4qCqs1xQmh0Hws83xQxofSApzVRScSCEi9Pg";
var get_product_default = defineTool2({
  name: "get_product",
  title: "D\xE9tail d\u2019un produit",
  description: 'R\xE9cup\xE8re la fiche compl\xE8te d\u2019un produit Rif Elegance par son slug (ex: "chapeau-paille-capeline-naturel") : description, mati\xE8re, entretien, artisan, dimensions, stock, prix.',
  inputSchema: {
    slug: z2.string().min(1).describe("Slug URL du produit")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ slug }) => {
    const supabase = createClient2(SUPABASE_URL2, SUPABASE_ANON2, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("products").select(
      "id, slug, name, price, category, description, short_description, details, care, material, dimensions_cm, weight_grams, color, artisan, artisan_story, images, stock_quantity, is_available, rating_average, rating_count"
    ).eq("slug", slug).eq("is_active", true).maybeSingle();
    if (error)
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    if (!data)
      return {
        content: [{ type: "text", text: `Aucun produit avec le slug "${slug}".` }],
        isError: true
      };
    return {
      content: [{ type: "text", text: `${data.name} \u2014 ${data.price} \u20AC` }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
var SUPABASE_URL3 = "https://xcvlijchkmhjonhfildm.supabase.co";
var SUPABASE_ANON3 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdmxpamNoa21oam9uaGZpbGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDY3MDEsImV4cCI6MjA2MzE4MjcwMX0.3_FZWbV4qCqs1xQmh0Hws83xQxofSApzVRScSCEi9Pg";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Lister les cat\xE9gories",
  description: "Retourne la liste distincte des cat\xE9gories de produits disponibles dans le catalogue Rif Elegance, avec le nombre de produits par cat\xE9gorie.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async () => {
    const supabase = createClient3(SUPABASE_URL3, SUPABASE_ANON3, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("products").select("category").eq("is_active", true);
    if (error)
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const c = row.category;
      counts.set(c, (counts.get(c) ?? 0) + 1);
    }
    const categories = [...counts.entries()].map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count);
    return {
      content: [
        { type: "text", text: `${categories.length} cat\xE9gories.` }
      ],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "rif-elegance-mcp",
  title: "Rif Elegance \u2014 Catalogue MCP",
  version: "0.1.0",
  instructions: "Outils publics en lecture seule pour explorer le catalogue Rif Elegance (chapeaux et accessoires en paille artisanaux du Rif). Utilise `search_products` pour trouver des produits, `get_product` pour la fiche d\xE9taill\xE9e d\u2019un slug, et `list_categories` pour lister les cat\xE9gories disponibles.",
  tools: [search_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
