// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values for preview/CI environments where .env may not be injected
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  'https://xcvlijchkmhjonhfildm.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdmxpamNoa21oam9uaGZpbGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDY3MDEsImV4cCI6MjA2MzE4MjcwMX0.3_FZWbV4qCqs1xQmh0Hws83xQxofSApzVRScSCEi9Pg';

console.info('[ENV CHECK]', {
  url: !!SUPABASE_URL,
  key: !!SUPABASE_PUBLISHABLE_KEY,
  fromEnv: !!import.meta.env.VITE_SUPABASE_URL,
});

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '[Supabase] Missing configuration — app will run in degraded mode'
  );
}

// Guest session key constant
const GUEST_SESSION_KEY = 'guest_session';

function clearSupabaseAuthStorage() {
  try {
    const keysToRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (
        key &&
        (key.startsWith('sb-') || key.startsWith('supabase.auth.'))
      ) {
        keysToRemove.push(key);
      }
    }
    keysToRemove.forEach((key) => localStorage.removeItem(key));
    if (keysToRemove.length > 0) {
      console.warn(
        `[SupabaseFetch] Cleared ${keysToRemove.length} stale auth key(s)`
      );
    }
  } catch {
    // localStorage may be unavailable (private mode), ignore
  }
}

/**
 * Get the current guest ID from storage (if exists)
 * This is called DYNAMICALLY on each request via the fetch wrapper,
 * NOT frozen at init time — prevents 42501 RLS errors.
 */
const getGuestId = (): string => {
  try {
    const raw = localStorage.getItem(GUEST_SESSION_KEY);
    if (raw) {
      const session = JSON.parse(raw);
      // Support all storage formats:
      // - Direct: { guestId: "..." } or { guest_id: "..." }
      // - safeStorage wrapper: { data: { guestId: "..." }, timestamp: ..., ttl: ... }
      // - Legacy wrapper: { value: { guestId: "..." } }
      const id =
        session?.guestId ||
        session?.guest_id ||
        session?.data?.guestId ||
        session?.data?.guest_id ||
        session?.value?.guestId ||
        session?.value?.guest_id;
      if (id) return id;
    }
  } catch {
    // Ignore parse errors
  }
  return '';
};

function createDynamicFetch(options: {
  timeoutMs: number;
  clearAuthOnAuthError?: boolean;
  retryOnceAfterAuthError?: boolean;
}) {
  const {
    timeoutMs,
    clearAuthOnAuthError = false,
    retryOnceAfterAuthError = false,
  } =
    options;

  const doFetch = async (
    url: RequestInfo | URL,
    init?: RequestInit,
    hasRetried = false
  ): Promise<Response> => {
    const guestId = getGuestId();
    const headers = new Headers(init?.headers);
    if (guestId) {
      headers.set('x-guest-id', guestId);
    }

    const controller = new AbortController();
    const existingSignal = init?.signal;
    const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

    if (existingSignal) {
      existingSignal.addEventListener('abort', () => controller.abort());
    }

    const urlStr =
      typeof url === 'string'
        ? url
        : url instanceof URL
          ? url.href
          : '(Request)';
    const shortUrl = urlStr.includes('supabase.co')
      ? urlStr.split('supabase.co')[1]?.substring(0, 60)
      : urlStr.substring(0, 80);

    try {
      console.info(`[SupabaseFetch] → ${shortUrl}`);
      const response = await fetch(url, {
        ...init,
        headers,
        signal: controller.signal,
      });
      clearTimeout(timeoutId);
      console.info(`[SupabaseFetch] ← ${response.status} ${shortUrl}`);

      if (
        (response.status === 401 || response.status === 403) &&
        clearAuthOnAuthError
      ) {
        console.warn(
          `[SupabaseFetch] ${response.status} detected — clearing stale auth tokens`
        );
        clearSupabaseAuthStorage();

        // Retry once after cleanup to avoid forcing the user into a manual reload.
        // hasRetried guards against loops when the server keeps rejecting.
        if (retryOnceAfterAuthError && !hasRetried) {
          console.warn(
            '[SupabaseFetch] Retrying request once after auth storage cleanup'
          );
          return doFetch(url, init, true);
        }
      }

      return response;
    } catch (err) {
      clearTimeout(timeoutId);
      console.error(`[SupabaseFetch] ✘ ${shortUrl}`, err?.message || err);
      throw err;
    }
  };

  return (url: RequestInfo | URL, init?: RequestInit) => doFetch(url, init);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      // Auth-aware client: handles stale JWT poisoning and retries once after cleanup.
      fetch: createDynamicFetch({
        timeoutMs: 15_000,
        clearAuthOnAuthError: true,
        retryOnceAfterAuthError: true,
      }),
    },
    realtime: {
      params: {
        eventsPerSecond: 2,
      },
      timeout: 30000,
      heartbeatIntervalMs: 30000,
    },
  }
);

// Public client for anonymous/public read flows.
// Intentionally does not persist auth session so stale JWT cannot poison
// products/blog/artisans requests in embedded preview environments.
export const supabasePublic = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
    global: {
      fetch: createDynamicFetch({
        timeoutMs: 10_000,
        clearAuthOnAuthError: false,
        retryOnceAfterAuthError: false,
      }),
    },
  }
);
