// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcvlijchkmhjonhfildm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdmxpamNoa21oam9uaGZpbGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDY3MDEsImV4cCI6MjA2MzE4MjcwMX0.3_FZWbV4qCqs1xQmh0Hws83xQxofSApzVRScSCEi9Pg";

// Guest session key constant
const GUEST_SESSION_KEY = 'guest_session';

/**
 * Get the current guest ID from storage (if exists)
 * This is called DYNAMICALLY on each request, not frozen at init time
 */
const getGuestId = (): string => {
  try {
    const raw = localStorage.getItem(GUEST_SESSION_KEY);
    if (raw) {
      const session = JSON.parse(raw);
      // Support both camelCase (from useGuestSession hook) and snake_case formats
      const id = session?.guestId || session?.guest_id || session?.value?.guestId || session?.value?.guest_id;
      if (id) return id;
    }
  } catch {
    // Ignore parse errors
  }
  return '';
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    // 🔒 FIX: Use a function to dynamically resolve x-guest-id on EVERY request
    // Previously this was frozen at initialization, causing 401s when guest ID
    // wasn't yet generated
    fetch: (url: RequestInfo | URL, options?: RequestInit) => {
      const guestId = getGuestId();
      const headers = new Headers(options?.headers);
      if (guestId) {
        headers.set('x-guest-id', guestId);
      }
      return fetch(url, { ...options, headers });
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 2,
    },
    timeout: 30000,
    heartbeatIntervalMs: 30000,
  },
});

/**
 * Create a supabase client with specific guest ID for checkout operations
 * This ensures the guest_id header is current at the time of the request
 */
export const createGuestClient = () => {
  const guestId = getGuestId();
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'x-guest-id': guestId
      }
    }
  });
};
